name: bitsdojo_window_windows_v3
description: Windows implementation of the bitsdojo_window plugin.
version: 3.0.1
homepage: https://www.bitsdojo.com
repository: https://github.com/DartGit-dev/bitsdojo_window

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window_platform_interface_v3:
    git:
      url: https://github.com/yalong0521/bitsdojo_window_platform_interface_v3.git
  win32: "^5.0.5"
  ffi: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: BitsdojoWindowPlugin
